### ISSUE TITLE
Improve the local development experience

### ISSUE THREAD

**Issue by ludelafo** [swiss-ai-center/chatbot-ollama-service#1]

**Comment by ludelafo** [comment]
Hey @Kayzz99,

I instinctively opened this issue and its related PR to comply to the elements we talked this morning that you can find here: https://github.com/swiss-ai-center/documentation/issues/30.

TL;DR: Improve the local development experience with the help of Docker and Docker Compose to easily start a service and start development.

Do you think it makes sense in this repository? Could you update/provide the files to comply to this proposition?

If you think it's not worth it, you can close the related PR and this issue.

**Comment by Kayzz99** [comment]
Hello @ludelafo ,
I already provided a docker compose file for a local deployement with ollama and the chatbot UI , do you think we need something more ?

**Comment by ludelafo** [comment]
Sorry for the late reply. I think we're good!
